linters-settings:
  lll:
    line-length: 180

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G306:"

linters:
  enable-all: true
  disable:
    - testpackage
    - forbidigo
    - paralleltest
    - exhaustivestruct
    - varnamelen
    - interfacer
    - maligned
    - scopelint
    - golint
    - varcheck
    - nosnakecase
    - deadcode
    - ifshort
    - structcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
    - exhaustruct
    - nolintlint
    - wrapcheck
    - funlen
    - depguard
    - wsl
    - tagliatelle
    - stylecheck
    - noctx
    - nlreturn
    - gomnd
    - err113
    - gocognit
    - gci
    - goconst
    - gocyclo
    - godot
    - godox
    - gofumpt
    - nestif
    - revive
    - cyclop
    - maintidx
    - forcetypeassert
